name: Bug Report
description: File a bug report
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows
        - MacOS (Arm)
        - MacOS (x64)
        - Linux
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the problem in as much detail as possible. If you have screenshots or screen recordings, please add them - they will help us figure out what's going on.
      placeholder: "When I do [something], [a strange thing or a bug] happens instead of [what I expected]."
    validations:
      required: true
  - type: textarea
    id: steps-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please mention the Steps to reproduce the Issue
      placeholder: " 1. Go to '...' \n 2. Click on '....' \n 3. Scroll down to '....' \n 4. See error"
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
